### ISSUE TITLE
Bug: Exception when running `fluence provider cc-info`

### ISSUE THREAD

**Issue by jcace** [fluencelabs/cli#853]
Repro steps:
After setting up a Provider, Registering and Activating Capacity Commitment, run the command `fluence provider cc-info`

It will prompt for wallet connection. After connecting the wallet in the browser, it results in the `Error: TypeError: Cannot read properties of undefined (reading 'args')` error. 

```
Using dar blockchain environment
To continue, please connect your wallet using metamask by opening the following url:

https://cli-connector.fluence.dev/?wc=xxx

or go to https://cli-connector.fluence.dev and enter the following connection string there:

wc:axxx

Error: TypeError: Cannot read properties of undefined (reading 'args')
    at file:///root/.local/share/fluence/client/0.15.22-789dbd0/dist/commands/provider/cc-info.js:43:54
    at Array.map (<anonymous>)
    at CCInfo.run (file:///root/.local/share/fluence/client/0.15.22-789dbd0/dist/commands/provider/cc-info.js:40:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CCInfo._run (/root/.local/share/fluence/client/0.15.22-789dbd0/node_modules/@oclif/core/lib/command.js:304:22)
    at async Config.runCommand (/root/.local/share/fluence/client/0.15.22-789dbd0/node_modules/@oclif/core/lib/config/config.js:417:25)
    at async Object.run (/root/.local/share/fluence/client/0.15.22-789dbd0/node_modules/@oclif/core/lib/main.js:85:16)
    ```

**Comment by shamsartem** [comment]
Sorry for the very late response. At this point we completely removed walletconnect so it should be a lot more reliable now. Thanks for the report
