### ISSUE TITLE
run `fluence deploy myDeployment` get error

### ISSUE THREAD

**Issue by andywu1998** [fluencelabs/cli#903]
hi all 

I try to deploy my First Cloudless Function by reading this article https://fluence.dev/docs/build/quickstarts/your_first_function

and then I got message like this 

```
andy at andys-MacBook-Air in ~/code/fluencedemo/hello-world
$ fluence deploy myDeployment
Using dar blockchain environment
    Finished release [optimized] target(s) in 0.12s
Service memory limits for worker myDeployment:
myService: 2.00 GB

Connecting to random dar relay: /dns4/4-dar.fluence.dev/tcp/9000/wss/p2p/12D3KooWJbJFaZ3k5sNd8DjQgg3aERoKtBAnirEvPV8yp76kEXHB
Connected

Creating myDeployment deal

/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-utils/dist/cjs/error.js:60
        ? new Error(`Unavailable ${type} RPC url at ${url}`)
          ^

Error: Unavailable WS RPC url at wss://relay.walletconnect.com
    at Object.parseConnectionError (/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-utils/dist/cjs/error.js:60:11)
    at l.parseError (/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-ws-connection/dist/index.cjs.js:1:2816)
    at l.emitError (/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-ws-connection/dist/index.cjs.js:1:2960)
    at WebSocket.<anonymous> (/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-ws-connection/dist/index.cjs.js:1:2262)
    at WebSocket.emit (node:events:517:28)
    at emitErrorAndClose (/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:895:13)
    at _NodeClientRequest.<anonymous> (/Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:752:5)
    at _NodeClientRequest.emit (node:events:529:35)
    at _NodeClientRequest.emit (file:///Users/andy/.local/share/fluence/client/0.16.2-37dfe47/node_modules/@mswjs/interceptors/lib/node/chunk-YXLNUCS2.mjs:410:18)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)

Node.js v18.20.1
```

thank you all.

**Comment by shamsartem** [comment]
Sorry for the very late response. At this point we completely removed walletconnect from cli. Now the signing with your wallet part should be a lot more reliable. Thanks for the report
